### ISSUE TITLE
Move locations for panel fiducials

### ISSUE THREAD

**Issue by arctictron** [sparkfun/SparkFun_KiCad_Panelizer#15]
Can we update the x or y positions for the panel fiducials so that they are closer to the inside of the panel? In other words, if the fiducials are located on the north and south side rails/borders, change the y position, and if they are on the east and west side rails/borders, change the x position.

The reason I am requesting this if we have finally had some panels made in KiCad make it through the new AOI machine which seem to have a slightly larger board clamps then the rest of our machines, so its hard to capture the fiducial in its entirety. The edge clearance we need is a minimum of 3mm.

**Comment by PaulZC** [comment]
@arctictron @nseidle : This is fixed. Please upgrade your Panelizer manually using the pre-release zip file:

https://github.com/sparkfun/SparkFun_KiCad_Panelizer/releases/tag/v1.3.1

https://github.com/sparkfun/SparkFun_KiCad_Panelizer/releases/download/v1.3.1/SparkFunKiCadPanelizer-1.3.1-pcm.zip

**Notes:**

The easiest / cleanest way to resolve this was to increase the width of the rails from 1/2" to 3/8". With the 3mm fiducial in the center of the rail, the clearance is just over 3mm. I hope that's OK? Let me know if not.

To keep the 1/2" rails, we'd need to add some nasty fixes to nudge the fiducial off-center. This could / would make life difficult for anyone running the panelizer from the command line.

**Comment by PaulZC** [comment]
Actually... Nah... I don't like the increased rail width. It's going to increase the area and weight of the board - and associated shipping costs - by about 8%...

I'm going to keep the rails at 1/4" and nudge the fiducial by 1/4 of the rail width.

Watch this space!

**Comment by PaulZC** [comment]
OK. Now we're in business... Happy?

![image](https://github.com/user-attachments/assets/540c699f-e622-4a22-ad07-0afadd158443)
