### ISSUE TITLE
JLCPCB

### ISSUE THREAD

**Issue by MKucukturkmen** [sparkfun/SparkFun_KiCad_Panelizer#5]
Hello, I created a panel and I wanted to have this panel produced by JLCPCB. In the Gerber Viewer tab on this site, the PCBs appear to be stuck together, but if I have them produced, they will be produced as a panel, right?

**Comment by PaulZC** [comment]
Hi,

We use JLCPCB all the time, and they have made panels for us using the output of this tool. See the [mosaic-X5](https://www.sparkfun.com/products/23088) and its [panel files](https://github.com/sparkfun/SparkFun_GNSS_mosaic-X5/tree/main/Hardware/Production).

The PCBs are separated by v-score lines:

![image](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/assets/5690545/95de35a1-b89f-4c18-a861-fde768ae08cd)

So long as those are shown correctly in the GKO outline, all will be well:

![image](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/assets/5690545/324b8fa1-261e-46c5-a913-0a6a8014911a)

It is a good idea to always check the gerber files by eye using the KiCad Gerber Viewer before you upload to JLCPCB.

There is an updated version of this tool on the [releases page](https://github.com/sparkfun/SparkFun_KiCad_Panelizer/releases). You will need to install it manually, it is not yet in the PCM. Instructions are [here](https://github.com/sparkfun/SparkFun_KiCad_Panelizer#installation-and-usage).

Best wishes,
Paul

**Comment by PaulZC** [comment]
Please note:

We wrote a separate [CAMmer](https://github.com/sparkfun/SparkFun_KiCad_CAMmer) to generate the gerber files and zip them into a single file for JLCPCB. This tool combines the v-scores and board edge into the panel outline GKO file. It is not in the PCM, you will need to install it manually. Download the latest release from [here](https://github.com/sparkfun/SparkFun_KiCad_CAMmer/releases). Installation instructions are [here](https://github.com/sparkfun/SparkFun_KiCad_CAMmer#installation-and-usage).

I hope this helps,
Paul

**Comment by MKucukturkmen** [comment]
Thank you very much Paul, you have created a really great tool, simple and functional. In the delivery format section, do we select the single pcb format right?

**Comment by PaulZC** [comment]
Hi Mustafa,

Correct, you select single PCB.

The SparkFun CAMmer is now available through the KiCad Plugin Content Manager (PCM). The Panelizer has been updated too. You can install the latest version of both through the PCM.

Please do remember to select both the board edge (outline) and v-score layer in the CAMmer. By default, the Panelizer puts the v-score lines in the User.Comments layer. But the latest version of the Panelizer allows you to change this if needed. Select the same layer in the CAMmer. I do recommend checking the GKO file before you upload to JLCPCB, just to make sure the v-scores have been included correctly.

Best wishes,
Paul
